---
response: "Homer"
tcpchecks:
  - name: marge.simpson
    host: marge-service.simpson
    port: 8080
  - name: selma.bouvier
    host: selma-service.bouvier
    port: 8080
  - name: patty.bouvier
    host: patty-service.bouvier
    port: 8080
