---
response: "Selma"
tcpchecks:
  - name: marge.simpson
    host: marge-service.simpson
    port: 8080
  - name: homer.simpson
    host: homer-service.simpson
    port: 8080
  - name: patty.bouvier
    host: patty-service.bouvier
    port: 8080
  - name: external-ibm
    host: www.ibm.com
    port: 80
